# config.mk
#
# Product-specific compile-time definitions.
#
TARGET_BOARD_PLATFORM := exynos4
TARGET_SOC := exynos4x12
#$(info TARGET_BOARD_PLATFORM = $(TARGET_BOARD_PLATFORM))

# CPU options
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true
TARGET_NO_RADIOIMAGE := true
TARGET_PROVIDES_INIT_TARGET_RC := true
TARGET_BOOTLOADER_BOARD_NAME := origen_quad

BOARD_USES_GENERIC_AUDIO := false
#BOARD_USES_GENERIC_AUDIO := true
#BOARD_HAVE_BLUETOOTH := true
BOARD_USES_SAMSUNG_AUDIO_HW := false
BOARD_USES_TINY_AUDIO_HW := false
BOARD_USES_ALSA_AUDIO := true
#BUILD_WITH_ALSA_UTILS := true
BOARD_USES_LEGACY_ALSA_AUDIO := true
BOARD_USES_AUDIO_CODEC := rt5631

# SEC Camera
USE_SEC_CAMERA := true

# Enable JIT
WITH_JIT := true

BOARD_HAS_TWOSTORAGES := true
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 314572800
BOARD_USERDATAIMAGE_PARTITION_SIZE := 14994636800
BOARD_FLASH_BLOCK_SIZE := 4096

BOARD_USES_HGL := true
BOARD_NO_32BPP := true

BOARD_USES_LIBPEONY := true

BOARD_USES_HDMI_SUBTITLES := false
BOARD_USES_HDMI := true
BOARD_HDMI_STD := STD_1080P
BOARD_HDMI_DDC_CH := DDC_CH_I2C_2
BOARD_USES_FIMGAPI := true

BOARD_USE_SAMSUNG_COLORFORMAT := true
BOARD_NONBLOCK_MODE_PROCESS := true
BOARD_USE_STOREMETADATA := true
BOARD_USE_METADATABUFFERTYPE := true
BOARD_USES_MFC_FPS := true
BOARD_USE_S3D_SUPPORT := true
BOARD_USE_CSC_FIMC := false

BOARD_USES_HIGH_RESOLUTION_LCD := false

# Enable V4L2 & ION
BOARD_USE_V4L2 := false
BOARD_USE_V4L2_ION := false

SCREEN_WIDTH := 800
SCREEN_HEIGHT := 480
DEFAULT_FB_NUM := 0

USE_OPENGL_RENDERER := true

TARGET_HAL_PATH := hardware/samsung/exynos4/hal
TARGET_OMX_PATH := hardware/samsung/exynos/multimedia/openmax
#TARGET_OMX_PATH := hardware/samsung/exynos/multimedia/openmax/sec_omx

CONNECTIVITY_SOLUTION := mtk
CONNECTIVITY_MODULE := mt6620

BOARD_USE_SENSOR := true

wifi_module_config := device/insignal/origen_quad/$(CONNECTIVITY_MODULE)/config.mk

-include $(wifi_module_config)

